// <auto-generated />
using core_cosmo_cs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace corecosmocs.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20170909014852_UpdateScoreToResult")]
    partial class UpdateScoreToResult
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("core_cosmo_cs.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ResultViewModelId");

                    b.Property<string>("Score");

                    b.HasKey("Id");

                    b.HasIndex("ResultViewModelId");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("core_cosmo_cs.Models.ResultViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("filePath");

                    b.Property<string>("jsonResult")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("core_cosmo_cs.Models.Result", b =>
                {
                    b.HasOne("core_cosmo_cs.Models.ResultViewModel")
                        .WithMany("scores")
                        .HasForeignKey("ResultViewModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
